---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-8
spec:
  containers:
    - name: mysql
      image: mysql:8
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: root119
        - name: MYSQL_DATABASE
          value: adithyadb
        - name: MYSQL_USER
          value: adithya
        - name: MYSQL_PASSWORD
          value: adithya119
---

# Service info is injected as env variables in all the pods to be created