FROM python:3.8-alpine3.15     
ADD . flask/
WORKDIR /flask
EXPOSE 8080        
RUN pip install -r requirements.txt
ENTRYPOINT ["python","app.py"]



# git clone https://github.com/DevProjectsForDevOps/StudentCoursesRestAPI.git    # do this using jenkins job  # it will directly take you inside this dir
# cd StudentCoursesRestAPI
# pip install -r requirements.txt
# python app.py

# ---
# base image required which has python with pip3 installed
# flask app runs on port 8080