# this file is wrt db-practice.yml file

# echo -n "db-name" | base64
# this outputs some random password xyz
# the standard base64 is available in most linux distributions
# we use the -n option to make sure that the new line symbol (\n) is not included in the encoded value

apiVersion: v1
kind: Secret
metadata:
  name: db-credentials     # give this name in the env.value field of the rs yml file
type: Opaque              # this is the default type
data:
  db-name: # give the encoded value here
  db-user:
  db-pass:
  db-root-pass:



# Opaque is the default Secret type if omitted from a Secret configuration file. When you create a Secret using kubectl, you will - 
# use the generic subcommand to indicate an Opaque Secret type. For example, the following command creates an empty Secret of type - 
# Opaque.

# kubectl create secret generic empty-secret

# kubectl get secret empty-secret
# NAME           TYPE     DATA   AGE
# empty-secret   Opaque   0      2m6s
# The DATA column shows the number of data items stored in the Secret. In this case, 0 means you have created an empty Secret.
