---
apiVersion: v1
kind: Pod
metadata:
  name: liveness-demo
  labels:
    purpose: liveness
spec:
  containers:
    - name: nginx
      image: nginx:1.21
      ports:
        - containerPort: 80
          protocol: TCP
      livenessProbe:
        httpGet:
          path: /            # give some wrong path here to make the cont fail & observe the behavior
          port: 80
        initialDelaySeconds: 5   # remember this option because all other options have default values.
        timeoutSeconds: 2       # remeber other options for explanation purpose.
        periodSeconds: 15     
        failureThreshold: 5
---

# Observations:
# kubelet restarts the container every 75 seconds:- (I did not factor in the initialDelaySeconds & timeoutSeconds)
# k8s runs the probe every 15 secs (periodSecinds) & runs it for 5 times (failureThreshold) & the probe marks the cont as unresponsive. -
# After seeing that the cont is unresponsive, now k8s restarts the pod & this cycle goes on until k8s stops restarting - 
# the pod i.e., after 5 consecutive restarts (default config of k8s ~) & changes the status of the pod to "CrashLoopBackoff" 

# initialDelaySeconds - start health checks 'x' seconds after the container has been started
# timeoutSeconds      - number of seconds after which the probe times out. Defaults to 1 second. Minimum value is 1.
# periodSeconds       - How often (in seconds) to perform the probe. Default to 10 seconds. Minimum value is 1.
# failureThreshold    - Minimum consecutive failures for the probe to be considered failed. Defaults to 3. Minimum value is 1.