---
apiVersion: v1
kind: Pod
metadata:
  name: limits-request-demo
spec:
  containers:
    - name: nginx
      image: nginx:1.21
      ports:
        - containerPort: 80
          protocol: TCP
      resources:
        requests:
          cpu: "500m"
          memory: "256Mi"
        limits:
          cpu: "1000m"
          memory: "512Mi"
---

# refer notes for explanation