# db pods.

# The scheduler will place 1 redis Pod per node if & only if that node has the label "kubernetes.io/hostname" & has atleast 1 pod - 
# with label app:nginx in it.

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-pods
spec:
  replicas: 2    # <refer notes at bottom>
  selector:
    matchLabels:
      db: redis
  template:
    metadata:
      labels:
        db: redis
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app     # the label(s) given here should match the labels given in spec.template.metadata.labels of web-pods.yml file
                operator: In
                values:
                - nginx
            topologyKey: "kubernetes.io/hostname"
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: db     # the label(s) given here should match the labels given in spec.template.metadata.labels of this file.
                operator: In
                values: 
                - redis
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: redis
        image: redis
---

# I've see that if you don't give replicas, k8s is assuming the desired pods is 1 even though I have 2 nodes.
# Hence, I have 2 replicas
# I have given 3 replicas & observed that the 3rd pod is not "running" because the anti-affinity rule was kicking in (only 1 pod per node)
