# Node affinity weight

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-affinity-weight
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-affinity-weight
  template:
    metadata:
      labels:
        app: node-affinity-weight
    spec:
      affinity:
        nodeAffinity:             
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:      # give "-" wherever you think there's a chance of plurality
              - key: kubernetes.io/os       # both worker nodes have this label
                operator: In
                values:                                 
                - linux
          preferredDuringSchedulingIgnoredDuringExecution:      # 2 rules with diff weights mentioned here
          - weight: 1     
            preference:
              matchExpressions:
              - key: cada-group     
                operator: In
                values:                                 
                - seo-unix-operations
          - weight: 50     
            preference:
              matchExpressions:
              - key: itrc-app    
                operator: In
                values:                                 
                - steel-cloud-vm
      containers:
      - name: node-affinity-weight
        image: nginx    

---

# both nodes have the "requiredDuringScheduling" label - 
# but k8s deployed all 3 pods in the 1 node which has "itrc-app:steel-cloud-vm" label because k8s kept score of all -
# nodes & the node with this label has the highest score (because weight is 50)

# The node that is most preferred is the one with the greatest sum of weights, i.e. for each node that meets all - 
# - of the scheduling requirements (resource request, requiredDuringScheduling affinity expressions & weight of preferredDuringSchedulingIgnoredDuringExecution)
# The node(s) with the highest sum are the most preferred.


# Note:
# If 3 of the worker nodes have the "required" label "itrc-app: ccp-vm" & none of them have the good-to-have label "app-group: cog-non-prod" - 
# the deployment will create the replicas on all 3 nodes coz required labels are found. The field "preferredDuringSchedulingIgnoredDuringExecution" -
# just provides extra control over the deployment logic
