apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: mysql-claim    # call it by its name which is defined in rs.yml
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2     # I think this is not required
  resources:
    requests:     # min value. Give "limits" for max value
      storage: 1Gi

# inside spec, remember only accessModes & resources