# mysql db pods --> check blog for yaml with extra spec (just to make it longer)

---
apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysqldb
          image: mysql:8
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: india123
            - name: MYSQL_DATABASE
              value: qtcommerce
            - name: MYSQL_USER
              value: qtdevops
            - name: MYSQL_PASSWORD
              value: india123
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-volume
              mountPath: "/var/lib/mysql"
      volumes: 
        - name: mysql-volume
          persistentVolumeClaim:
            claimName: mysql-claim
---


# svc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
spec:
  selector:
    app: mysql
  type: LoadBalancer
  ports:
    - port: 3306
      targetPort: 3306
---