pipeline {
    agent { 
        label 'k8s_master'      /* running this on k8s_master, which is a slave to Jenkins */
        }              
    stages {
        
        stage('scm/git') {
            steps {
                url: 'https://github.com/Adithya119/K8s_2023.git', changelog: false, poll: false, git branch: 'master'
            }
        }

        stage('build') {
            steps {
                sh '''cd 13-Flask-hostpath/
                ls
                kubectl apply -f secrets.yml
                kubectl get secrets'''
            }
        }
    }
}